spring.application.name=IntegratingOpenAI

#setup for openAI
spring.ai.openai.api-key=${OPENAI_KEY_VALUE}
#spring.ai.openai.chat.options.model=gpt-4.1
#spring.ai.openai.chat.options.temperature=0.2
spring.ai.openai.chat.model=gpt-4.1
spring.ai.openai.chat.temperature=0.2
